#!/bin/bash

ALL=$1

echo "Available USB camera devices:"
for path in /dev/v4l/by-id/usb-*-video-index0; do
    if [[ "$ALL" == "--all" ]]; then
        echo
        echo "=== $path ==="
        echo
        v4l2-ctl --device "$path" --all --list-formats --list-formats-ext
    else
        echo "  $path"
    fi
done
