#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root/with sudo"
  exit 1
fi

NAME=$1

if [ -z "$NAME" ]; then
  echo "Usage: $0 <name>"
  exit 1
fi

if [ ! -e "/boot/camera-streamer/usb-$NAME.conf" ]; then
  echo "Camera $NAME does not exist"
  exit 1
fi

/usr/local/bin/camera-streamer-control stop $NAME

rm /boot/camera-streamer/usb-$NAME.conf
rm /run/systemd/system/camera-streamer-usb-$NAME.path || true
systemctl daemon-reload
