name: "🧑‍💻 Internal: Dev Task"
description: Only use this issue type if you are a maintainer or collaborator of OctoPi-UpToDate!
title: "[Task] "
labels: ["task"]
body:
  - type: textarea
    attributes:
      label: "The task"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Verification
      options:
        - label: I'm a maintainer or collaborator of OctoPi-UpToDate and allowed to use this issue type
          required: true
